name: Build and Release Image


on:
  pull_request:


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: edc-ui
  IMAGE_NAME_BASE: ${{ github.repository_owner }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      - name: Log in to the Container registry (push-only)
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Store latest commit's author, message and SHA
        run: |
          echo "Start storing"
          touch src/assets/.version
          ls src/assets
          git log -1 > src/assets/.version
          git log -1
          echo "${{github.sha}}"
          echo "${{github.event.pull_request.head.sha}}"
          cat src/assets/.version

